#!/usr/bin/env python3
"""Merge per-unit question JSON files into questions.js (window.QUESTIONS)."""
import json, sys
from pathlib import Path

UNITS = {
    1: "Unit 1 · Alignment",
    2: "Unit 2 · Breath Control",
    3: "Unit 3 · Initiation, Creation & Release of Sound",
    4: "Unit 4 · Resonance",
    5: "Unit 5 · Consonants",
    6: "Unit 6 · Vowels",
    7: "Unit 7 · Vibrato",
    8: "Unit 8 · Registers",
}

src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("data")
out = []
for n, name in UNITS.items():
    for item in json.loads((src / f"unit{n}.json").read_text()):
        assert len(item["distractors"]) == 3 and item["correct"] not in item["distractors"], item["q"]
        out.append({"unit": name, "q": item["q"], "correct": item["correct"],
                    "distractors": item["distractors"], "explain": item["explain"],
                    "source": item.get("source", "book")})

root = Path(__file__).resolve().parent.parent
(root / "questions.js").write_text(
    "// Generated by scripts/build_questions.py — edit data/unit*.json instead.\n"
    "window.QUESTIONS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
print(len(out), "questions written")
